import React, { Fragment } from "react";
import MainLayout from "../../MainLayout4";

export const metadata = {
  title: "Products |",
  description: "Generated by Organichatt products",
};

export default function ProductLayout({ breadcrmb, sidebar, children }) {
  return (
    <Fragment>
      {breadcrmb}
      <div className=" xl:px-20 2lg:px-5 2md:px-20 md:px-10 sm:px-5 px-3 py-10 flex gap-5">
        <div className=" 2lg:w-[20%] 2lg:block hidden">{sidebar}</div>

        <div className=" 2lg:w-[80%] w-full">{children}</div>
      </div>
    </Fragment>
  );
}
