export const GET_ALL_CATEGORY_FOR_MANUS = "GET_ALL_CATEGORY_FOR_MANUS";
export const GET_ERRORS = "GET_ERRORS";
export const GET_CARTS = "GET_CARTS";
export const GET_CART_PRODUCT_COUNT = "GET_CART_PRODUCT_COUNT";
export const GET_FAVORITE_PRODUCT_COUNT = "GET_FAVORITE_PRODUCT_COUNT";
export const GET_FAVORITES = "GET_FAVORITES";
export const GET_PRODUCT_FOR_MODAL = "GET_PRODUCT_FOR_MODAL";
