export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const GET_ERRORS = "GET_ERRORS";
export const GET_HERO_BANNER = "GET_HERO_BANNER";
export const GET_OFFER_BANNERS = "GET_OFFER_BANNERS";
export const GET_OUR_CATEGORIES = "GET_OUR_CATEGORIES";
