import React, { Fragment } from "react";
import MainLayout from "../../MainLayout4";

export const metadata = {
  title: "Contact |",
  description: "Generated by Organichatt Contact",
};

export default function ContactLayout({ breadcrmb, contactinfo, children }) {
  return (
    <Fragment>
      {breadcrmb}
      <div className=" xl:px-20 lg:px-[5.5rem] 2md:px-[5.5rem] md:px-[3rem] sm:px-[1.5rem] 4xs:px-7 px-5 pt-10 pb-20">
        <div className="lg:flex gap-5">
          {contactinfo}
          {children}
        </div>
      </div>
    </Fragment>
  );
}
