import React from "react";
import ProductDetailsContent from "./components/ProductDetailsContent";

export const metadata = {
  title: "Product Details |",
  description: "Generated by Organichatt products",
};

export default function ProductDetails() {
  return <ProductDetailsContent />;
}
