import { Inter } from "next/font/google";
import "./globals.css";
import "./main.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Organichatt",
    template: "%s Organichatt",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" cz-shortcut-listen="true">
      <body className={inter.className} cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
